### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by SpaghettiC0des** [karlmarxlopez/useStateWithLayoutAnimation#1]
Using `Jest` and `react-native-testing-library`.

### Tasks
- [ ] test `setState.spring`
- [ ] test `setState.linear`
- [ ] test `setState.easeInEaseOut`
- [ ] test `setState.noAnimation`

**Comment by dangercharles** [comment]
Good code

**Comment by SpaghettiC0des** [comment]
@dangercharles Thank you! If you are interested, you can take this issue. 🙂

**Comment by shtelzerartem** [comment]
@karlmarxlopez Hey, thank you for the great library, can I take this task? :)

**Comment by eavam** [comment]
I can take it :)

**Comment by SpaghettiC0des** [comment]
Sure @eavam ! Let me know if you have questions. Thank you.

**Comment by eavam** [comment]
@karlmarxlopez [PR](https://github.com/karlmarxlopez/useStateWithLayoutAnimation/pull/5) is ready 😁

**Comment by SpaghettiC0des** [comment]
@eavam I'll review it tomorrow. Thanks!
